<?php
/**
 * News.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\NewsModule\Api\Base;

use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerAwareTrait;
use Zikula_AbstractBase;

/**
 * Mailz api base class.
 */
abstract class AbstractMailzApi extends Zikula_AbstractBase implements ContainerAwareInterface
{
    use ContainerAwareTrait;

    /**
     * MailzApi constructor.
     */
    public function __construct()
    {
        $this->setContainer(\ServiceUtil::getManager());
    }

    /**
     * Returns existing Mailz plugins with type / title.
     *
     * @param array $args List of arguments
     *
     * @return array List of provided plugin functions
     */
    public function getPlugins(array $args = [])
    {
        $translator = $this->container->get('translator.default');
    
        $plugins = [];
        $plugins[] = [
            'pluginid'      => 1,
            'module'        => 'MUNewsModule',
            'title'         => $translator->__('3 newest messages'),
            'description'   => $translator->__('A list of the three newest messages.')
        ];
        $plugins[] = [
            'pluginid'      => 2,
            'module'        => 'MUNewsModule',
            'title'         => $translator->__('3 random messages'),
            'description'   => $translator->__('A list of three random messages.')
        ];
    
        return $plugins;
    }
    
    /**
     * Returns the content for a given Mailz plugin.
     *
     * @param array    $args                List of arguments
     * @param int      $args['pluginid']    id number of plugin (internal id for this module, see getPlugins method)
     * @param string   $args['params']      optional, show specific one or all otherwise
     * @param int      $args['uid']         optional, user id for user specific content
     * @param string   $args['contenttype'] h or t for html or text
     * @param datetime $args['last']        timestamp of last newsletter
     *
     * @return string output of plugin template
     */
    public function getContent(array $args = [])
    {
        // $args is something like:
        // Array ( [uid] => 5 [contenttype] => h [pluginid] => 1 [nid] => 1 [last] => 0000-00-00 00:00:00 [params] => Array ( [] => ) ) 1
        $objectType = 'message';
    
        $repository = $this->container->get('mu_news_module.entity_factory')->getRepository($objectType);
    
        $sorting = 'default';
        if ($args['pluginid'] == 2) {
            $sorting = 'random';
        } elseif ($args['pluginid'] == 1) {
            $sorting = 'newest';
        }
        $sortParam = $this->container->get('mu_news_module.model_helper')->resolveSortParameter($objectType, $sorting);
    
        $where = ''/*$this->filter*/;
        $resultsPerPage = 3;
    
        // get objects from database
        try {
            list($entities, $objectCount) = $repository->selectWherePaginated($where, $orderBy, 1, $resultsPerPage);
        } catch (\Exception $exception) {
            $entities = [];
            $objectCount = 0;
        }
    
        $templateType = $args['contenttype'] == 't' ? 'text' : 'html';
    
        //$templateParameters = ['sorting' => $this->sorting, 'amount' => $this->amount, 'filter' => $this->filter, 'template' => $this->template];
        $templateParameters = [
            'objectType' => $objectType,
            'items' => $entities
        ];
    
        $templateParameters = $this->container->get('mu_news_module.controller_helper')->addTemplateParameters($objectType, $templateParameters, 'mailz', []);
    
        return $this->container->get('twig')->render(
            '@MUNewsModule/Mailz/itemlist_' . $objectType . $templateType . '.twig',
            $templateParameters
        );
    }
}
