<?php

/**
 * News.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @see https://homepages-mit-zikula.de
 * @see https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\NewsModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use MU\NewsModule\Entity\MessageEntity;

/**
 * Event base class for filtering message processing.
 */
class AbstractFilterMessageEvent extends Event
{
    /**
     * @var MessageEntity Reference to treated entity instance.
     */
    protected $message;

    /**
     * @var array Entity change set for preUpdate events.
     */
    protected $entityChangeSet = [];

    public function __construct(MessageEntity $message, array $entityChangeSet = [])
    {
        $this->message = $message;
        $this->entityChangeSet = $entityChangeSet;
    }

    /**
     * @return MessageEntity
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * @return array Entity change set
     */
    public function getEntityChangeSet()
    {
        return $this->entityChangeSet;
    }
}
