<?php
/**
 * News.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
<<<<<<< HEAD
 * @version Generated by ModuleStudio 1.3.2 (https://modulestudio.de) at Wed Aug 15 20:24:48 CEST 2018.
=======
 * @version Generated by ModuleStudio 1.3.2 (https://modulestudio.de) at Thu Jun 28 20:31:57 CEST 2018.
>>>>>>> 9a25b877e13c36ac1561ed548b54e635e7ff6590
 */

/**
 * Bootstrap called when application is first initialised at runtime.
 *
 * This is only called once, and only if the core has reason to initialise this module,
 * usually to dispatch a controller request or API.
 */

require_once __DIR__ . '/../vendor/autoload.php';
