<?php

/**
 * News.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 *
 * @see https://homepages-mit-zikula.de
 * @see https://ziku.la
 *
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

declare(strict_types=1);

namespace MU\NewsModule\ContentType\Base;

use Zikula\ExtensionsModule\ModuleInterface\Content\AbstractContentType;
use MU\NewsModule\ContentType\Form\Type\ItemListType as FormType;
use MU\NewsModule\Entity\Factory\EntityFactory;
use MU\NewsModule\Helper\CategoryHelper;
use MU\NewsModule\Helper\ControllerHelper;
use MU\NewsModule\Helper\FeatureActivationHelper;
use MU\NewsModule\Helper\ModelHelper;
use MU\NewsModule\Helper\PermissionHelper;

/**
 * Generic item list content type base class.
 */
abstract class AbstractItemListType extends AbstractContentType
{
    /**
     * @var ControllerHelper
     */
    protected $controllerHelper;
    
    /**
     * @var ModelHelper
     */
    protected $modelHelper;
    
    /**
     * @var PermissionHelper
     */
    protected $modulePermissionHelper;
    
    /**
     * @var EntityFactory
     */
    protected $entityFactory;
    
    /**
     * @var FeatureActivationHelper
     */
    protected $featureActivationHelper;
    
    /**
     * @var CategoryHelper
     */
    protected $categoryHelper;
    
    /**
     * List of object types allowing categorisation.
     *
     * @var array
     */
    protected $categorisableObjectTypes;
    
    public function getIcon(): string
    {
        return 'th-list';
    }
    
    public function getTitle(): string
    {
        return $this->translator->trans('News list');
    }
    
    public function getDescription(): string
    {
        return $this->translator->trans('Display a list of news objects.');
    }
    
    public function getDefaultData(): array
    {
        return [
            'objectType' => 'message',
            'sorting' => 'default',
            'amount' => 1,
            'template' => 'itemlist_display.html.twig',
            'customTemplate' => null,
            'filter' => ''
        ];
    }
    
    public function getData(): array
    {
        $data = parent::getData();
    
        $contextArgs = ['name' => 'list'];
        $allowedObjectTypes = $this->controllerHelper->getObjectTypes('contentType', $contextArgs);
        if (
            !isset($data['objectType'])
            || !in_array($data['objectType'], $allowedObjectTypes, true)
        ) {
            $data['objectType'] = $this->controllerHelper->getDefaultObjectType('contentType', $contextArgs);
        }
    
        if (!isset($data['template'])) {
            $data['template'] = 'itemlist_' . $data['objectType'] . '_display.html.twig';
        }
    
        $objectType = $data['objectType'];
        $this->categorisableObjectTypes = ['message'];
        if ($this->featureActivationHelper->isEnabled(FeatureActivationHelper::CATEGORIES, $objectType)) {
            $primaryRegistry = $this->categoryHelper->getPrimaryProperty($objectType);
            if (!isset($data['categories'])) {
                $data['categories'] = [$primaryRegistry => []];
            } else {
                if (!is_array($data['categories'])) {
                    $data['categories'] = explode(',', $data['categories']);
                }
                if (count($data['categories']) > 0) {
                    $firstCategories = reset($data['categories']);
                    if (!is_array($firstCategories)) {
                        $firstCategories = [$firstCategories];
                    }
                    $data['categories'] = [$primaryRegistry => $firstCategories];
                }
            }
        }
        $this->data = $data;
    
        return $data;
    }
    
    public function displayView(): string
    {
        $objectType = $this->data['objectType'];
        $repository = $this->entityFactory->getRepository($objectType);
    
        // create query
        $orderBy = $this->modelHelper->resolveSortParameter($this->data['objectType'], $this->data['sorting']);
        $qb = $repository->getListQueryBuilder($this->data['filter'], $orderBy);
    
        $this->getData();
        if (in_array($objectType, $this->categorisableObjectTypes, true)) {
            if ($this->featureActivationHelper->isEnabled(FeatureActivationHelper::CATEGORIES, $objectType)) {
                // apply category filters
                if (is_array($this->data['categories']) && count($this->data['categories']) > 0) {
                    $qb = $this->categoryHelper->buildFilterClauses($qb, $objectType, $this->data['categories']);
                }
            }
        }
    
        // get objects from database
        $currentPage = 1;
        $resultsPerPage = isset($this->data['amount']) ? $this->data['amount'] : 1;
        $paginator = $repository->retrieveCollectionResult($qb, true, $currentPage, $resultsPerPage);
        $entities = $paginator->getResults();
    
        // filter by permissions
        $entities = $this->modulePermissionHelper->filterCollection($objectType, $entities, ACCESS_READ);
    
        $data = $this->data;
        $data['items'] = $entities;
    
        $data = $this->controllerHelper->addTemplateParameters($objectType, $data, 'contentType', []);
        $this->data = $data;
    
        return parent::displayView();
    }
    
    public function getViewTemplatePath(string $suffix = ''): string
    {
        $templateFile = $this->data['template'];
        if (
            'custom' === $templateFile
            && null !== $this->data['customTemplate']
            && '' !== $this->data['customTemplate']
        ) {
            $templateFile = $this->data['customTemplate'];
        }
    
        $templateForObjectType = str_replace('itemlist_', 'itemlist_' . $this->data['objectType'] . '_', $templateFile);
    
        $templateOptions = [
            'ContentType/' . $templateForObjectType,
            'ContentType/' . $templateFile,
            'ContentType/itemlist_display.html.twig'
        ];
    
        $template = '';
        foreach ($templateOptions as $templatePath) {
            if ($this->twigLoader->exists('@MUNewsModule/' . $templatePath)) {
                $template = '@MUNewsModule/' . $templatePath;
                break;
            }
        }
    
        return $template;
    }
    
    public function getEditFormClass(): string
    {
        return FormType::class;
    }
    
    public function getEditFormOptions($context): array
    {
        $options = parent::getEditFormOptions($context);
        $data = $this->getData();
        $options['object_type'] = $data['objectType'];
        $this->categorisableObjectTypes = ['message'];
        $options['is_categorisable'] = in_array($this->data['objectType'], $this->categorisableObjectTypes);
        $options['category_helper'] = $this->categoryHelper;
        $options['feature_activation_helper'] = $this->featureActivationHelper;
    
        return $options;
    }
    
    /**
     * @required
     */
    public function setControllerHelper(ControllerHelper $controllerHelper): void
    {
        $this->controllerHelper = $controllerHelper;
    }
    
    /**
     * @required
     */
    public function setModelHelper(ModelHelper $modelHelper): void
    {
        $this->modelHelper = $modelHelper;
    }
    
    /**
     * @required
     */
    public function setModulePermissionHelper(PermissionHelper $modulePermissionHelper): void
    {
        $this->modulePermissionHelper = $modulePermissionHelper;
    }
    
    /**
     * @required
     */
    public function setEntityFactory(EntityFactory $entityFactory): void
    {
        $this->entityFactory = $entityFactory;
    }
    
    /**
     * @required
     */
    public function setCategoryDependencies(
        CategoryHelper $categoryHelper,
        FeatureActivationHelper $featureActivationHelper
    ): void {
        $this->categoryHelper = $categoryHelper;
        $this->featureActivationHelper = $featureActivationHelper;
    }
}
