<?php
/**
 * MUNews.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license 
 * @package MUNews
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * This class provides object meta data for the Tag module.
 */
class MUNews_TaggedObjectMeta_MUNews extends MUNews_TaggedObjectMeta_Base_MUNews
{
    // feel free to extend the tag support here
}
