<?php

/**
 * News.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @see https://homepages-mit-zikula.de
 * @see https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

declare(strict_types=1);

namespace MU\NewsModule\Form\Type\Finder\Base;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\SearchType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Translation\Extractor\Annotation\Ignore;
use Zikula\Bundle\FormExtensionBundle\Form\Type\LocaleType;
use Zikula\CategoriesModule\Form\Type\CategoriesType;
use Zikula\ExtensionsModule\Api\ApiInterface\VariableApiInterface;
use MU\NewsModule\Helper\FeatureActivationHelper;

/**
 * Message finder form type base class.
 */
abstract class AbstractMessageFinderType extends AbstractType
{
    /**
     * @var RequestStack
     */
    protected $requestStack;

    /**
     * @var VariableApiInterface
     */
    protected $variableApi;

    /**
     * @var FeatureActivationHelper
     */
    protected $featureActivationHelper;

    public function __construct(
        
        RequestStack $requestStack,
        VariableApiInterface $variableApi,
        FeatureActivationHelper $featureActivationHelper
    ) {
        $this->requestStack = $requestStack;
        $this->variableApi = $variableApi;
        $this->featureActivationHelper = $featureActivationHelper;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->setMethod('GET')
            ->add('objectType', HiddenType::class, [
                'data' => $options['object_type']
            ])
            ->add('editor', HiddenType::class, [
                'data' => $options['editor_name']
            ])
        ;

        if ($this->variableApi->getSystemVar('multilingual')) {
            $this->addLanguageField($builder, $options);
        }
        if ($this->featureActivationHelper->isEnabled(FeatureActivationHelper::CATEGORIES, $options['object_type'])) {
            $this->addCategoriesField($builder, $options);
        }
        $this->addImageFields($builder, $options);
        $this->addPasteAsField($builder, $options);
        $this->addSortingFields($builder, $options);
        $this->addAmountField($builder, $options);
        $this->addSearchField($builder, $options);

        $builder
            ->add('update', SubmitType::class, [
                'label' => 'Change selection',
                'icon' => 'fa-check',
                'attr' => [
                    'class' => 'btn-success'
                ]
            ])
            ->add('cancel', SubmitType::class, [
                'label' => 'Cancel',
                'validate' => false,
                'icon' => 'fa-times'
            ])
        ;
    }

    /**
     * Adds a language field.
     */
    public function addLanguageField(FormBuilderInterface $builder, array $options = [])
    {
        $builder->add('language', LocaleType::class, [
            'label' => 'Language:',
            'data' => $this->requestStack->getCurrentRequest()->getLocale(),
            'empty_data' => null,
            'multiple' => false,
            'expanded' => false
        ]);
    }

    /**
     * Adds a categories field.
     */
    public function addCategoriesField(FormBuilderInterface $builder, array $options = []): void
    {
        $entityCategoryClass = 'MU\NewsModule\Entity\\' . ucfirst($options['object_type']) . 'CategoryEntity';
        $builder->add('categories', CategoriesType::class, [
            'label' => 'Categories:',
            'empty_data' => [],
            'attr' => [
                'class' => 'category-selector',
                'title' => 'This is an optional filter.'
            ],
            'help' => 'This is an optional filter.',
            'required' => false,
            'multiple' => true,
            'module' => 'MUNewsModule',
            'entity' => ucfirst($options['object_type']) . 'Entity',
            'entityCategoryClass' => $entityCategoryClass,
            'showRegistryLabels' => true
        ]);
    }

    /**
     * Adds fields for image insertion options.
     */
    public function addImageFields(FormBuilderInterface $builder, array $options = []): void
    {
        $builder->add('onlyImages', CheckboxType::class, [
            'label' => 'Only images',
            'label_attr' => [
                'class' => 'switch-custom'
            ],
            'empty_data' => false,
            'help' => 'Enable this option to insert images',
            'required' => false
        ]);
        $builder->add('imageField', ChoiceType::class, [
            'label' => 'Image field',
            'empty_data' => 'imageUpload1',
            'help' => 'You can switch between different image fields',
            'choices' => [
                'Image upload 1' => 'imageUpload1',
                'Image upload 2' => 'imageUpload2',
                'Image upload 3' => 'imageUpload3',
                'Image upload 4' => 'imageUpload4'
            ],
            'multiple' => false,
            'expanded' => false
        ]);
    }

    /**
     * Adds a "paste as" field.
     */
    public function addPasteAsField(FormBuilderInterface $builder, array $options = []): void
    {
        $builder->add('pasteAs', ChoiceType::class, [
            'label' => 'Paste as:',
            'empty_data' => 1,
            'choices' => [
                'Relative link to the message' => 1,
                'Absolute url to the message' => 2,
                'ID of message' => 3,
                'Relative link to the image' => 6,
                'Image' => 7,
                'Image with relative link to the message' => 8,
                'Image with absolute url to the message' => 9
            ],
            'multiple' => false,
            'expanded' => false
        ]);
    }

    /**
     * Adds sorting fields.
     */
    public function addSortingFields(FormBuilderInterface $builder, array $options = []): void
    {
        $builder
            ->add('sort', ChoiceType::class, [
                'label' => 'Sort by:',
                'empty_data' => '',
                'choices' => [
                    'Workflow state' => 'workflowState',
                    'Title' => 'title',
                    'Image upload 1' => 'imageUpload1',
                    'Display on index' => 'displayOnIndex',
                    'Creation date' => 'createdDate',
                    'Creator' => 'createdBy',
                    'Update date' => 'updatedDate',
                    'Updater' => 'updatedBy'
                ],
                'multiple' => false,
                'expanded' => false
            ])
            ->add('sortdir', ChoiceType::class, [
                'label' => 'Sort direction:',
                'empty_data' => 'asc',
                'choices' => [
                    'Ascending' => 'asc',
                    'Descending' => 'desc'
                ],
                'multiple' => false,
                'expanded' => false
            ])
        ;
    }

    /**
     * Adds a page size field.
     */
    public function addAmountField(FormBuilderInterface $builder, array $options = []): void
    {
        $builder->add('num', ChoiceType::class, [
            'label' => 'Page size:',
            'empty_data' => 20,
            'attr' => [
                'class' => 'text-right'
            ],
            /** @Ignore */
            'choices' => [
                5 => 5,
                10 => 10,
                15 => 15,
                20 => 20,
                30 => 30,
                50 => 50,
                100 => 100
            ],
            'multiple' => false,
            'expanded' => false
        ]);
    }

    /**
     * Adds a search field.
     */
    public function addSearchField(FormBuilderInterface $builder, array $options = []): void
    {
        $builder->add('q', SearchType::class, [
            'label' => 'Search for:',
            'required' => false,
            'attr' => [
                'maxlength' => 255
            ]
        ]);
    }

    public function getBlockPrefix()
    {
        return 'munewsmodule_messagefinder';
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver
            ->setDefaults([
                'object_type' => 'message',
                'editor_name' => 'ckeditor',
                'translation_domain' => 'message'
            ])
            ->setRequired(['object_type', 'editor_name'])
            ->setAllowedTypes('object_type', 'string')
            ->setAllowedTypes('editor_name', 'string')
            ->setAllowedValues('editor_name', ['ckeditor', 'quill', 'summernote', 'tinymce'])
        ;
    }
}
