<?php
/**
 * News.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\NewsModule\Form\Handler\Common;

use MU\NewsModule\Form\Handler\Common\Base\AbstractEditHandler;

/**
 * This handler class handles the page events of editing forms.
 * It collects common functionality required by different object types.
 */
abstract class EditHandler extends AbstractEditHandler
{
    /**
     * Return list of attribute field names.
     * To be customised in sub classes as needed.
     *
     * @return array list of attribute names
     */
    protected function getAttributeFieldNames()
    {
        return [
            'morearticlesincat', 'field2', 'field3'
        ];
    }
}
