<?php

/**
 * News.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @see https://homepages-mit-zikula.de
 * @see https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

declare(strict_types=1);

namespace MU\NewsModule\Event;

use MU\NewsModule\Event\Base\AbstractItemActionsMenuPostConfigurationEvent;

/**
 * Event implementation class for extending item actions menu.
 */
class ItemActionsMenuPostConfigurationEvent extends AbstractItemActionsMenuPostConfigurationEvent
{
    // feel free to extend the event class here
}
