<?php
/**
 * News.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\NewsModule\Event;

use MU\NewsModule\Event\Base\AbstractFilterMessageEvent;

/**
 * Event implementation class for filtering message processing.
 */
class FilterMessageEvent extends AbstractFilterMessageEvent
{
    // feel free to extend the event class here
}
