<?php

/**
 * News.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 *
 * @see https://homepages-mit-zikula.de
 * @see https://ziku.la
 *
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

declare(strict_types=1);

namespace MU\NewsModule\ContentType\Form\Type\Base;

use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Translation\Extractor\Annotation\Ignore;
use Translation\Extractor\Annotation\Translate;
use Zikula\ExtensionsModule\ModuleInterface\Content\ContentTypeInterface;
use Zikula\ExtensionsModule\ModuleInterface\Content\Form\Type\AbstractContentFormType;
use MU\NewsModule\Entity\Factory\EntityFactory;
use MU\NewsModule\Helper\EntityDisplayHelper;

/**
 * Detail content type form type base class.
 */
abstract class AbstractItemType extends AbstractContentFormType
{
    /**
     * @var EntityFactory
     */
    protected $entityFactory;

    /**
     * @var EntityDisplayHelper
     */
    protected $entityDisplayHelper;

    public function __construct(
        EntityFactory $entityFactory,
        EntityDisplayHelper $entityDisplayHelper
    ) {
        $this->entityFactory = $entityFactory;
        $this->entityDisplayHelper = $entityDisplayHelper;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $this->addObjectTypeField($builder, $options);
        $this->addIdField($builder, $options);
        $this->addDisplayModeField($builder, $options);
        $this->addTemplateField($builder, $options);
    }

    /**
     * Adds an object type field.
     */
    public function addObjectTypeField(FormBuilderInterface $builder, array $options = []): void
    {
        $builder->add('objectType', HiddenType::class, [
            'label' => 'Object type:',
            'empty_data' => 'message',
        ]);
    }

    /**
     * Adds a item identifier field.
     */
    public function addIdField(FormBuilderInterface $builder, array $options = []): void
    {
        $repository = $this->entityFactory->getRepository($options['object_type']);
        // select without joins
        $entities = $repository->selectWhere('', '', false);
    
        $choices = [];
        foreach ($entities as $entity) {
            $choices[$this->entityDisplayHelper->getFormattedTitle($entity)] = $entity->getKey();
        }
        ksort($choices);
    
        $builder->add('id', ChoiceType::class, [
            'multiple' => false,
            'expanded' => false,
            'choices' => /** @Ignore */$choices,
            'required' => true,
            'label' => 'Entry to display:',
        ]);
    }

    /**
     * Adds a display mode field.
     */
    public function addDisplayModeField(FormBuilderInterface $builder, array $options = []): void
    {
        $builder->add('displayMode', ChoiceType::class, [
            'label' => 'Display mode:',
            'label_attr' => [
                'class' => 'radio-custom',
            ],
            'empty_data' => 'embed',
            'choices' => [
                'Link to object' => 'link',
                'Embed object display' => 'embed',
            ],
            'multiple' => false,
            'expanded' => true,
        ]);
    }

    /**
     * Adds template fields.
     */
    public function addTemplateField(FormBuilderInterface $builder, array $options = []): void
    {
        $builder
            ->add('customTemplate', TextType::class, [
                'label' => 'Custom template:',
                'required' => false,
                'attr' => [
                    'maxlength' => 80,
                    /** @Ignore */
                    'title' => /** @Translate */'Example' . ': displaySpecial.html.twig',
                ],
                /** @Ignore */
                'help' => [
                    /** @Translate */'Example' . ': <code>displaySpecial.html.twig</code>',
                    /** @Translate */'Needs to be located in the "External/YourEntity/" directory.',
                ],
                'help_html' => true,
            ])
        ;
    }

    public function getBlockPrefix()
    {
        return 'munewsmodule_contenttype_detail';
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver
            ->setDefaults([
                'context' => ContentTypeInterface::CONTEXT_EDIT,
                'object_type' => 'message',
            ])
            ->setRequired(['object_type'])
            ->setAllowedTypes('context', 'string')
            ->setAllowedTypes('object_type', 'string')
            ->setAllowedValues('context', [ContentTypeInterface::CONTEXT_EDIT, ContentTypeInterface::CONTEXT_TRANSLATION])
        ;
    }
}
