<?php
/**
 * News.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\NewsModule;

use MU\NewsModule\Base\AbstractNewsEvents;

/**
 * Events definition implementation class.
 */
class NewsEvents extends AbstractNewsEvents
{
    // feel free to extend the events definition here
}
