<?php

/**
 * News.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */
namespace MU\NewsModule\Helper;

use MU\NewsModule\Helper\Base\AbstractNotificationHelper;

/**
 * Notification helper implementation class.
 */
class NotificationHelper extends AbstractNotificationHelper
{
    /**
     * Sends a mail to either an item's creator or a group of moderators.
     *
     * @return boolean
     */
    public function process($args)
    {
        $request = $this->requestStack->getCurrentRequest();
        $zkFunc = $request->attributes->get('_zkFunc');

        if ('display' !== $zkFunc) {
            return parent::process($args);
        }

        return '';
    }
}
