<?php

/**
 * News.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */
namespace MU\NewsModule\Helper;

use MU\NewsModule\Helper\Base\AbstractNotificationHelper;
use Symfony\Component\HttpFoundation\Request;

/**
 * Notification helper implementation class.
 */
class NotificationHelper extends AbstractNotificationHelper {
	
	/**
	 * Sends a mail to either an item's creator or a group of moderators.
	 *
	 * @return boolean
	 */
	public function process($args)
	{
		$zkFunc = $this->request->attributes->get ( '_zkFunc' );
		
		if ($zkFunc != 'display') {
			$result = parent::process($args);
		} else {
			$result = '';
		}
	
		return $result;
	}
}
