<?php

/**
 * News.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @see https://homepages-mit-zikula.de
 * @see https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

declare(strict_types=1);

namespace MU\NewsModule\Menu;

use Knp\Menu\ItemInterface;
use MU\NewsModule\Menu\Base\AbstractExtensionMenu;

/**
 * This is the extension menu service implementation class.
 */
class ExtensionMenu extends AbstractExtensionMenu
{
    public function get(string $type = self::TYPE_ADMIN): ?ItemInterface
    {
        $menu = parent::get($type);
        if (null === $menu || self::TYPE_ADMIN !== $type) {
            return $menu;
        }

        if ($this->permissionHelper->hasPermission(ACCESS_ADMIN)) {
            $menu->addChild('Import old news', [
                'route' => 'munewsmodule_import_oldnewsarticles',
            ])
                ->setAttribute('icon', 'fas fa-file-import')
                ->setLinkAttribute('title', 'Import news entries from an old news site. For this to work your database must have a \'news\' table that was generated from the old news module')
            ;
        }

        return 0 === $menu->count() ? null : $menu;
    }
}
