<?php

/**
 * News.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @see https://homepages-mit-zikula.de
 * @see https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\NewsModule\Controller;

use MU\NewsModule\Controller\Base\AbstractMessageController;
use RuntimeException;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Zikula\Bundle\FormExtensionBundle\Form\Type\DeletionType;
use Zikula\Bundle\HookBundle\Category\FormAwareCategory;
use Zikula\Bundle\HookBundle\Category\UiHooksCategory;
use Zikula\Component\SortableColumns\Column;
use Zikula\Component\SortableColumns\SortableColumns;
use Zikula\Core\Controller\AbstractController;
use Zikula\Core\RouteUrl;
use Symfony\Component\Routing\Annotation\Route;
use Zikula\ThemeModule\Engine\Annotation\Theme;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use MU\NewsModule\Entity\MessageEntity;
use MU\NewsModule\Helper\FeatureActivationHelper;

/**
 * Message controller class providing navigation and interaction functionality.
 */
class MessageController extends AbstractMessageController
{
    /**
     * @inheritDoc
     *
     * @Route("/admin/messages",
     *        methods = {"GET"}
     * )
     * @Theme("admin")
     */
    public function adminIndexAction(
        Request $request
    ) {
        return $this->indexInternal($request, true);
    }
    
    /**
     * @inheritDoc
     *
     * @Route("/messages",
     *        methods = {"GET"}
     * )
     *
     */
    public function indexAction(
        Request $request
    ) {
        return $this->indexInternal($request, false);
    }
    
    /**
     * @inheritDoc
     *
     * @Route("/admin/messages/view/{sort}/{sortdir}/{pos}/{num}.{_format}",
     *        requirements = {"sortdir" = "asc|desc|ASC|DESC", "pos" = "\d+", "num" = "\d+", "_format" = "html|csv|rss|atom|xml|json|pdf"},
     *        defaults = {"sort" = "", "sortdir" = "asc", "pos" = 1, "num" = 10, "_format" = "html"},
     *        methods = {"GET"}
     * )
     * @Theme("admin")
     */
    public function adminViewAction(
        Request $request,
        $sort,
        $sortdir,
        $pos,
        $num
    ) {
        return $this->viewInternal($request, $sort, $sortdir, $pos, $num, true);
    }
    
    /**
     * @inheritDoc
     *
     * @Route("/messages/view/{sort}/{sortdir}/{pos}/{num}.{_format}",
     *        requirements = {"sortdir" = "asc|desc|ASC|DESC", "pos" = "\d+", "num" = "\d+", "_format" = "html|csv|rss|atom|xml|json|pdf"},
     *        defaults = {"sort" = "", "sortdir" = "asc", "pos" = 1, "num" = 10, "_format" = "html"},
     *        methods = {"GET"}
     * )
     */
    public function viewAction(
        Request $request,
        $sort,
        $sortdir,
        $pos,
        $num
    ) {
        return $this->viewInternal($request, $sort, $sortdir, $pos, $num, false);
    }
    
    /**
     * @inheritDoc
     *
     * @Route("/admin/message/edit/{id}.{_format}",
     *        requirements = {"id" = "\d+", "_format" = "html"},
     *        defaults = {"id" = "0", "_format" = "html"},
     *        methods = {"GET", "POST"}
     * )
     * @Theme("admin")
     */
    public function adminEditAction(
        Request $request
    ) {
        return $this->editInternal($request, true);
    }
    
    /**
     * @inheritDoc
     *
     * @Route("/message/edit/{id}.{_format}",
     *        requirements = {"id" = "\d+", "_format" = "html"},
     *        defaults = {"id" = "0", "_format" = "html"},
     *        methods = {"GET", "POST"}
     * )
     */
    public function editAction(
        Request $request
    ) {
        return $this->editInternal($request, false);
    }
    
    /**
     * @inheritDoc
     *
     * @Route("/admin/message/delete/{slug}.{_format}",
     *        requirements = {"slug" = "[^/.]+", "_format" = "html"},
     *        defaults = {"_format" = "html"},
     *        methods = {"GET", "POST"}
     * )
     * @ParamConverter("message", class="MUNewsModule:MessageEntity", options = {"repository_method" = "selectBySlug", "mapping": {"slug": "slugTitle"}, "map_method_signature" = true})
     * @Theme("admin")
     */
    public function adminDeleteAction(
        Request $request,
        $slug
    ) {
        return $this->deleteInternal($request, $slug, true);
    }
    
    /**
     * @inheritDoc
     *
     * @Route("/message/delete/{slug}.{_format}",
     *        requirements = {"slug" = "[^/.]+", "_format" = "html"},
     *        defaults = {"_format" = "html"},
     *        methods = {"GET", "POST"}
     * )
     * @ParamConverter("message", class="MUNewsModule:MessageEntity", options = {"repository_method" = "selectBySlug", "mapping": {"slug": "slugTitle"}, "map_method_signature" = true})
     */
    public function deleteAction(
        Request $request,
        $slug
    ) {
        return $this->deleteInternal($request, $slug, false);
    }
    
    /**
     * @inheritDoc
     *
     * @Route("/admin/message/{slug}.{_format}",
     *        requirements = {"slug" = "[^/.]+", "_format" = "html|xml|json|ics|pdf"},
     *        defaults = {"_format" = "html"},
     *        methods = {"GET"}
     * )
     * @ParamConverter("message", class="MUNewsModule:MessageEntity", options = {"repository_method" = "selectBySlug", "mapping": {"slug": "slugTitle"}, "map_method_signature" = true})
     * @Theme("admin")
     */
    public function adminDisplayAction(
        Request $request,
        MessageEntity $message = null,
        $slug = ''
    ) {
        return $this->displayInternal($request, $message, $slug, true);
    }
    
    /**
     * @inheritDoc
     *
     * @Route("/message/{slug}.{_format}",
     *        requirements = {"slug" = "[^/.]+", "_format" = "html|xml|json|ics|pdf"},
     *        defaults = {"_format" = "html"},
     *        methods = {"GET"}
     * )
     * @ParamConverter("message", class="MUNewsModule:MessageEntity", options = {"repository_method" = "selectBySlug", "mapping": {"slug": "slugTitle"}, "map_method_signature" = true})
     *
     * @param Request $request Current request instance
     * @param MessageEntity $message Treated message instance
     *
     *
     * @throws AccessDeniedException Thrown if the user doesn't have required permissions
     * @throws NotFoundHttpException Thrown by param converter if message to be displayed isn't found
     */
    public function displayAction(
        Request $request,
        MessageEntity $message = null,
        $slug = ''
    ) {
        return $this->displayInternal($request, $message, $slug, false);
    }
    
    /**
     * Process status changes for multiple items.
     *
     * This function processes the items selected in the admin view page.
     * Multiple items may have their state changed or be deleted.
     *
     * @Route("/admin/messages/handleSelectedEntries",
     *        methods = {"POST"}
     * )
     * @Theme("admin")
     */
    public function adminHandleSelectedEntriesAction(
        Request $request
    ) {
        return $this->handleSelectedEntriesActionInternal($request, true);
    }
    
    /**
     * Process status changes for multiple items.
     *
     * This function processes the items selected in the admin view page.
     * Multiple items may have their state changed or be deleted.
     *
     * @Route("/messages/handleSelectedEntries",
     *        methods = {"POST"}
     * )
     */
    public function handleSelectedEntriesAction(
        Request $request
    ) {
        return $this->handleSelectedEntriesActionInternal($request, false);
    }

    /**
     * Import news items from an old news site.
     *
     * @Route("/messages/importNewsArticles")
     *
     * @param Request $request Current request instance
     *
     *
     * @throws RuntimeException Thrown if executing the workflow action fails
     */
    public function importNewsArticlesAction(Request $request)
    {
        //check permission, only admins can do this.
        if (!$this->hasPermission('MUNewsModule::', '::', ACCESS_ADMIN)) {
            throw new AccessDeniedException($this->__('You do not have pemission to import news items. Admin access is needed.'));
        }

        //you must have a news table in your database for this to work.
        $entityManager = $this->container->get('doctrine.orm.default_entity_manager');
        //grab the connection
        $conn = $entityManager->getConnection();
        //Do an old style SQL select statement
        $sql = "SELECT * FROM news WHERE 1";
        $stmt = $conn->prepare($sql);
        $stmt->execute();

        // returns an array of arrays (i.e. a raw data set)
        $items = $stmt->fetchAll();
        //determine the number of items for reporting back to the user.
        $num_Items = count($items);
        //Grab a few things that I will need for filling in the messages
        //I am taking a shortcut here since the approver of past messages may not be on the site anymore
        //and instead I am using the current ID of the person that is importing the messages who is the admin.
        $currentUserApi = $this->get('zikula_users_module.current_user');
        $author_id = $currentUserApi->get('uid');
        $author = $currentUserApi->get('uname');
        $user = $entityManager->getRepository('Zikula\UsersModule\Entity\UserEntity')->findByUids($author_id);
        //walk the array and fill in the fields in the new data that are needed.
        foreach ($items as $item) {
            $message = new MessageEntity();
            $cr_date = new \DateTime($item['cr_date']);
            $lu_date = new \DateTime($item['lu_date']);
            $message->setTitle($item['title']);
            $message->setStartText($item['hometext']);
            $message->setMainText($item['bodytext']);
            $contributor = $item['contributor'];
            if ('' !== $contributor) {
                $message->setAuthor($contributor);
                // see if this person is still a user
            } else {
                $message->setAuthor($author);
            }
            $message->setCreatedBy($user[0]);
            $message->setUpdatedBy($user[0]);
            $message->setCreatedDate($cr_date);
            $message->setUpdatedDate($lu_date);
            $message->setDisplayOnIndex($item['displayonindex']);
            $message->setAllowComments($item['allowcomments']);
            $message->setStartDate($cr_date);
            $message->setNoEndDate(true);
            $message->setWeight(1);
            $message->setSlug($item['urltitle']);
            $message->setNotes($item['notes']);
            $message->setAmountOfViews($item['counter']);
            $message->setMessageLanguage($item['language']);
            $message->setWorkflowState('approved');
            $entityManager->persist($message);
        }
        //save back to the database.
        $entityManager->flush();
        $this->addFlash(
            'status',
            $this->__f('%amountOfMessages messages imported.', ['%amountOfMessages' => $num_Items])
        );

        return $this->redirectToRoute('munewsmodule_message_adminindex');
    }
}
