<?php
/**
 * News.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepage-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.0.1 (https://modulestudio.de).
 */

namespace MU\NewsModule\Form\Type\Hook;

use MU\NewsModule\Form\Type\Hook\Base\AbstractEditMessageType;

/**
 * Edit message form type implementation class.
 */
class EditMessageType extends AbstractEditMessageType
{
    // feel free to extend the base form type class here
}
