<?php

/**
 * News.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 *
 * @see https://homepages-mit-zikula.de
 * @see https://ziku.la
 *
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

declare(strict_types=1);

namespace MU\NewsModule\ContentType\Form\Type;

use MU\NewsModule\ContentType\Form\Type\Base\AbstractItemListType;

/**
 * List content type form type implementation class.
 */
class ItemListType extends AbstractItemListType
{
    // feel free to extend the list content type form type class here
}
