<?php
/**
 * News.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepage-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.0.1 (https://modulestudio.de).
 */

namespace MU\NewsModule\Listener;

use MU\NewsModule\Listener\Base\AbstractUsersListener;

/**
 * Event handler implementation class for events of the Users module.
 */
class UsersListener extends AbstractUsersListener
{
    // feel free to enhance the parent methods
}
