<?php
/**
 * MUNews.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license 
 * @package MUNews
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity extension domain class storing message categories.
 *
 * This is the concrete category class for message entities.
* @ORM\Entity(repositoryClass="MUNews_Entity_Repository_MessageCategory")
   * @ORM\Table(name="munews_message_category",
   *     uniqueConstraints={
   *         @ORM\UniqueConstraint(name="cat_unq", columns={"registryId", "categoryId", "entityId"})
   *     }
   * )
 */
class MUNews_Entity_MessageCategory extends MUNews_Entity_Base_MessageCategory
{
    // feel free to add your own methods here
}
