<?php

/**
 * News.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @see https://homepages-mit-zikula.de
 * @see https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

declare(strict_types=1);

namespace MU\NewsModule\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Contracts\Translation\TranslatorInterface;
use Zikula\Common\Translator\TranslatorTrait;
use MU\NewsModule\Entity\Factory\EntityFactory;
use MU\NewsModule\Entity\ImageEntity;
use MU\NewsModule\Form\Type\Field\UploadType;

/**
 * Image editing form type implementation class.
 */
class ImageType extends AbstractType
{
    use TranslatorTrait;

    /**
     * @var EntityFactory
     */
    protected $entityFactory;

    public function __construct(
        TranslatorInterface $translator,
        EntityFactory $entityFactory
    ) {
        $this->setTranslator($translator);
        $this->entityFactory = $entityFactory;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $imageEntity = new ImageEntity(); // TODO ??
        $builder->add('theFile', UploadType::class, [
            'label' => $this->__('The file') . ':',
            'attr' => [
                'class' => ' validate-upload',
                'title' => $this->__('Enter the the file of the image.')
            ],
            'required' => true && $options['mode'] == 'create',
            'entity' => $imageEntity,
            'allowed_extensions' => 'gif, jpeg, jpg, png',
            'allowed_size' => ''
        ]);
        $builder->add('caption', TextType::class, [
            'label' => $this->__('Caption') . ':',
            'empty_data' => '',
            'attr' => [
                'maxlength' => 255,
                'class' => '',
                'title' => $this->__('Enter the caption of the image.')
            ],
            'required' => false,
        ]);
        $builder->add('sortNumber', IntegerType::class, [
            'label' => $this->__('Sort number') . ':',
            'help' => $this->__f('Note: this value must not be lower than %minValue%.', ['%minValue%' => 1]),
            'empty_data' => 1,
            'attr' => [
                'maxlength' => 4,
                'class' => '',
                'min' => 1,
                'title' => $this->__('Enter the sort number of the image.')
                    . ' ' . $this->__('Only digits are allowed.')
            ],
            'required' => true,
            'scale' => 0
        ]);
    }

    public function getBlockPrefix()
    {
        return 'munewsmodule_image';
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver
            ->setDefaults([
                // define class for underlying data (required for embedding forms)
                'data_class' => ImageEntity::class,
                'empty_data' => function (FormInterface $form) {
                    return $this->entityFactory->createImage();
                },
                'error_mapping' => [
                    'theFile' => 'theFile.theFile',
                ],
                'mode' => 'create'
            ])
            ->setRequired(['mode'])
            ->setAllowedTypes('mode', 'string')
            ->setAllowedValues('mode', ['create', 'edit'])
        ;
    }
}
