<?php

/**
 * News.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @see https://homepages-mit-zikula.de
 * @see https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

declare(strict_types=1);

namespace MU\NewsModule\Helper;

use MU\NewsModule\Helper\Base\AbstractListEntriesHelper;

/**
 * Helper implementation class for list field entries related methods.
 */
class ListEntriesHelper extends AbstractListEntriesHelper
{
    public function getDefaultMessageSortingEntriesForAppSettings(): array
    {
        $states = parent::getDefaultMessageSortingEntriesForAppSettings();
        foreach ($states as $k => $state) {
            if ('articlestartdate' === $state['value']) {
                $states[$k]['default'] = true;
                break;
            }
        }

        return $states;
    }
}
