<?php
/**
 * MUNews.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license 
 * @package MUNews
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * Configuration handler implementation class.
 */
class MUNews_Form_Handler_Admin_Config extends MUNews_Form_Handler_Admin_Base_Config
{
    // feel free to extend the base handler class here
}
