<?php
/**
 * MUNews.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license
 * @package MUNews
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * Configuration handler implementation class.
 */
class MUNews_Form_Handler_Admin_Config extends MUNews_Form_Handler_Admin_Base_Config
{
    /**
     * Method stub for own additions in subclasses.
     */
    protected function initializeAdditions()
    {
        $dom = ZLanguage::getModuleDomain('MUNews');
        // we check for module MUImage and legacy mode on
        $muimage = ModUtil::available('MUImage');
        $legacy = System::isLegacyMode();

        if ($muimage == true && $legacy == true) {
            $useMUImage = true;
        } else {
            $useMUImage = false;
        }

        $this->view->assign('useMUImage', $useMUImage)
                   ->assign('muimage', $muimage)
                   ->assign('legacy', $legacy);
    }
}
