<?php

/**
 * News.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @see https://homepages-mit-zikula.de
 * @see https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

declare(strict_types=1);

namespace MU\NewsModule\Form\Handler\Message;

use MU\NewsModule\Form\Handler\Message\Base\AbstractEditHandler;

/**
 * This handler class handles the page events of editing forms.
 * It aims on the message object type.
 */
class EditHandler extends AbstractEditHandler
{
    // feel free to extend the base handler class here
}
