<?php

/**
 * News.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @see https://homepages-mit-zikula.de
 * @see https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

declare(strict_types=1);

namespace MU\NewsModule\DependencyInjection;

use MU\NewsModule\DependencyInjection\Base\AbstractMUNewsExtension;

/**
 * DependencyInjection extension implementation class.
 */
class MUNewsExtension extends AbstractMUNewsExtension
{
    // custom enhancements can go here
}
