<?php

/**
 * News.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 *
 * @see https://homepages-mit-zikula.de
 * @see https://ziku.la
 *
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

declare(strict_types=1);

namespace MU\NewsModule\Twig\Base;

use Twig\Extension\AbstractExtension;
use Twig\TwigFilter;
use Twig\TwigFunction;
use MU\NewsModule\Twig\TwigRuntime;

/**
 * Twig extension base class.
 */
abstract class AbstractTwigExtension extends AbstractExtension
{
    public function getFunctions()
    {
        return [
            new TwigFunction('munewsmodule_moderationObjects', [TwigRuntime::class, 'getModerationObjects']),
            new TwigFunction('munewsmodule_increaseCounter', [TwigRuntime::class, 'increaseCounter']),
            new TwigFunction('munewsmodule_objectTypeSelector', [TwigRuntime::class, 'getObjectTypeSelector']),
            new TwigFunction('munewsmodule_templateSelector', [TwigRuntime::class, 'getTemplateSelector']),
        ];
    }
    
    public function getFilters()
    {
        return [
            new TwigFilter('munewsmodule_fileSize', [TwigRuntime::class, 'getFileSize'], ['is_safe' => ['html']]),
            new TwigFilter('munewsmodule_relativePath', [TwigRuntime::class, 'getRelativePath']),
            new TwigFilter('munewsmodule_listEntry', [TwigRuntime::class, 'getListEntry']),
            new TwigFilter('munewsmodule_icalText', [TwigRuntime::class, 'formatIcalText']),
            new TwigFilter('munewsmodule_formattedTitle', [TwigRuntime::class, 'getFormattedEntityTitle']),
            new TwigFilter('munewsmodule_objectState', [TwigRuntime::class, 'getObjectState'], ['is_safe' => ['html']]),
        ];
    }
}
