<?php

/**
 * News.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @see https://homepages-mit-zikula.de
 * @see https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

declare(strict_types=1);

namespace MU\NewsModule\Listener;

use MU\NewsModule\Listener\Base\AbstractUserLogoutListener;

/**
 * Event handler implementation class for user logout events.
 */
class UserLogoutListener extends AbstractUserLogoutListener
{
    // feel free to enhance the parent methods
}
