<?php

/**
 * News.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @see https://homepages-mit-zikula.de
 * @see https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\NewsModule\Form\Type\Field;

use MU\NewsModule\Form\Type\Field\Base\AbstractMultiListType;

/**
 * Multi list field type implementation class.
 */
class MultiListType extends AbstractMultiListType
{
    // feel free to extend the base form type class here
}
