<?php
/**
 * News.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\NewsModule\TaggedObjectMeta;

use MU\NewsModule\TaggedObjectMeta\Base\AbstractMUNewsModule;

/**
 * This class provides object meta data for the Tag module.
 */
class MUNewsModule extends AbstractMUNewsModule
{
    // feel free to extend the tag support here
}
