<?php
/**
 * MUNews.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license 
 * @package MUNews
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * Repository class used to implement own convenience methods for performing certain DQL queries.
 *
 * This is the concrete repository class for message entities.
 */
class MUNews_Entity_Repository_Message extends MUNews_Entity_Repository_Base_Message
{
    /**
     * @var string The default sorting field/expression.
     */
    protected $defaultSortingField = 'createdDate';
}
