<?php
/**
 * News.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\NewsModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use MU\NewsModule\Entity\ImageEntity;

/**
 * Event base class for filtering image processing.
 */
class AbstractFilterImageEvent extends Event
{
    /**
     * @var ImageEntity Reference to treated entity instance.
     */
    protected $image;

    /**
     * @var array Entity change set for preUpdate events.
     */
    protected $entityChangeSet = [];

    public function __construct(ImageEntity $image, array $entityChangeSet = [])
    {
        $this->image = $image;
        $this->entityChangeSet = $entityChangeSet;
    }

    /**
     * @return ImageEntity
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * @return array Entity change set
     */
    public function getEntityChangeSet()
    {
        return $this->entityChangeSet;
    }
}
