<?php
/**
 * MUNews.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license 
 * @package MUNews
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * Validator class for encapsulating entity validation methods.
 *
 * This is the base validation class for message entities.
 */
class MUNews_Entity_Validator_Base_Message extends MUNews_Validator
{
    /**
     * Performs all validation rules.
     *
     * @return mixed either array with error information or true on success
     */
    public function validateAll()
    {
        $errorInfo = array('message' => '', 'code' => 0, 'debugArray' => array());
        $dom = ZLanguage::getModuleDomain('MUNews');
        if (!$this->isValidInteger('id')) {
            $errorInfo['message'] = __f('Error! Field value may only contain digits (%s).', array('id'), $dom);
            return $errorInfo;
        }
        if (!$this->isNumberNotLongerThan('id', 9)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('id', 9), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotEmpty('workflowState')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('workflow state'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('title', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('title', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotEmpty('title')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('title'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('startText', 3000)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('start text', 3000), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotEmpty('startText')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('start text'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('imageUpload1', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('image upload1', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('mainText', 10000)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('main text', 10000), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('imageUpload2', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('image upload2', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('imageUpload3', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('image upload3', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('imageUpload4', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('image upload4', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isValidInteger('muimageAlbum')) {
            $errorInfo['message'] = __f('Error! Field value may only contain digits (%s).', array('muimage album'), $dom);
            return $errorInfo;
        }
        if (!$this->isNumberNotLongerThan('muimageAlbum', 11)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('muimage album', 11), $dom);
            return $errorInfo;
        }
        if (!$this->isValidInteger('weight')) {
            $errorInfo['message'] = __f('Error! Field value may only contain digits (%s).', array('weight'), $dom);
            return $errorInfo;
        }
        if (!$this->isNumberNotEmpty('weight')) {
            $errorInfo['message'] = __f('Error! Field value must not be 0 (%s).', array('weight'), $dom);
            return $errorInfo;
        }
        if (!$this->isNumberNotLongerThan('weight', 2)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('weight', 2), $dom);
            return $errorInfo;
        }
        if (!$this->isValidBoolean('noEndDate')) {
            $errorInfo['message'] = __f('Error! Field value must be a valid boolean (%s).', array('no end date'), $dom);
            return $errorInfo;
        }
    
        return true;
    }
    
    /**
     * Check for unique values.
     *
     * This method determines if there already exist messages with the same message.
     *
     * @param string $fieldName The name of the property to be checked
     * @return boolean result of this check, true if the given message does not already exist
     */
    public function isUniqueValue($fieldName)
    {
        if ($this->entity[$fieldName] == '') {
            return false;
        }
    
        $entityClass = 'MUNews_Entity_Message';
        $serviceManager = ServiceUtil::getManager();
        $entityManager = $serviceManager->getService('doctrine.entitymanager');
        $repository = $entityManager->getRepository($entityClass);
    
        $excludeid = $this->entity['id'];
    
        return $repository->detectUniqueState($fieldName, $this->entity[$fieldName], $excludeid);
    }
    
    /**
     * Get entity.
     *
     * @return Zikula_EntityAccess
     */
    public function getEntity()
    {
        return $this->entity;
    }
    
    /**
     * Set entity.
     *
     * @param Zikula_EntityAccess $entity.
     *
     * @return void
     */
    public function setEntity(Zikula_EntityAccess $entity = null)
    {
        $this->entity = $entity;
    }
    
}
