<?php
/**
 * MUNews.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license 
 * @package MUNews
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity extension domain class storing message categories.
 *
 * This is the base category class for message entities.
 */
class MUNews_Entity_Base_MessageCategory extends Zikula_Doctrine2_Entity_EntityCategory
{
    /**
     * @ORM\ManyToOne(targetEntity="MUNews_Entity_Message", inversedBy="categories")
     * @ORM\JoinColumn(name="entityId", referencedColumnName="id")
     * @var MUNews_Entity_Message
     */
    protected $entity;

    /**
     * Get reference to owning entity.
     *
     * @return MUNews_Entity_Message
     */
    public function getEntity()
    {
        return $this->entity;
    }
    
    /**
     * Set reference to owning entity.
     *
     * @param MUNews_Entity_Message $entity
     */
    public function setEntity(/*MUNews_Entity_Message */$entity)
    {
        $this->entity = $entity;
    }
}
