<?php
/**
 * MUNews.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license 
 * @package MUNews
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * Upload handler implementation class.
 */
class MUNews_UploadHandler extends MUNews_Base_UploadHandler
{
    /**
     * Constructor initialising the supported object types.
     */
    public function __construct()
    {
        parent::__construct();

        $this->allowedFileSizes = array('message' => array('imageUpload1' => ModUtil::getVar('MUNews', 'allowedFileSize', 102400), 'imageUpload2' => ModUtil::getVar('MUNews', 'allowedFileSize', 102400), 'imageUpload3' => ModUtil::getVar('MUNews', 'allowedFileSize', 102400), 'imageUpload4' => ModUtil::getVar('MUNews', 'allowedFileSize', 102400)));
    }
}
