<?php
/**
 * MUNews.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license 
 * @package MUNews
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de) at Mon Feb 03 13:42:10 CET 2014.
 */

/**
 * Version information implementation class.
 */
class MUNews_Version extends MUNews_Base_Version
{
    // custom enhancements can go here
}
