<?php
/**
 * News.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\NewsModule\Entity;

use MU\NewsModule\Entity\Base\AbstractMessageAttributeEntity as BaseEntity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity extension domain class storing message attributes.
 *
 * This is the concrete attribute class for message entities.
 * @ORM\Entity(repositoryClass="\MU\NewsModule\Entity\Repository\MessageAttributeRepository")
 * @ORM\Table(name="mu_news_message_attribute",
 *     uniqueConstraints={
 *         @ORM\UniqueConstraint(name="cat_unq", columns={"name", "entityId"})
 *     }
 * )
 */
class MessageAttributeEntity extends BaseEntity
{
    // feel free to add your own methods here
}
