<?php

/**
 * News.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 *
 * @see https://homepages-mit-zikula.de
 * @see https://ziku.la
 *
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

declare(strict_types=1);

namespace MU\NewsModule\HookSubscriber\Base;

use Symfony\Contracts\Translation\TranslatorInterface;
use Zikula\Bundle\HookBundle\Category\FormAwareCategory;
use Zikula\Bundle\HookBundle\HookSubscriberInterface;

/**
 * Base class for form aware hook subscriber.
 */
abstract class AbstractMessageFormAwareHookSubscriber implements HookSubscriberInterface
{
    /**
     * @var TranslatorInterface
     */
    protected $translator;

    public function __construct(TranslatorInterface $translator)
    {
        $this->translator = $translator;
    }

    public function getOwner(): string
    {
        return 'MUNewsModule';
    }
    
    public function getCategory(): string
    {
        return FormAwareCategory::NAME;
    }
    
    public function getTitle(): string
    {
        return $this->translator->trans('Message form aware subscriber', [], 'hooks');
    }
    
    public function getAreaName(): string
    {
        return 'subscriber.munewsmodule.form_aware_hook.messages';
    }

    public function getEvents(): array
    {
        return [
            // Display hook for create/edit forms.
            FormAwareCategory::TYPE_EDIT => 'munewsmodule.form_aware_hook.messages.edit',
            // Process the results of the edit form after the main form is processed.
            FormAwareCategory::TYPE_PROCESS_EDIT => 'munewsmodule.form_aware_hook.messages.process_edit',
            // Display hook for delete forms.
            FormAwareCategory::TYPE_DELETE => 'munewsmodule.form_aware_hook.messages.delete',
            // Process the results of the delete form after the main form is processed.
            FormAwareCategory::TYPE_PROCESS_DELETE => 'munewsmodule.form_aware_hook.messages.process_delete',
        ];
    }
}
