<?php

/**
 * News.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @see https://homepages-mit-zikula.de
 * @see https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

declare(strict_types=1);

namespace MU\NewsModule;

use MU\NewsModule\Base\AbstractNewsModuleInstaller;
use MU\NewsModule\Entity\ImageEntity;

/**
 * Installer implementation class.
 */
class NewsModuleInstaller extends AbstractNewsModuleInstaller
{
    public function upgrade(string $oldVersion): bool
    {
        if ('1.0.0' === $oldVersion) {
            $this->addFlash('error', 'Update from 1.0.0 to 1.2.0+ is not supported. Please update to 1.1.0 first.');

            return false;
        }

        $logger = $this->container->get('logger');

        // Upgrade dependent on old version number
        switch ($oldVersion) {
            case '1.1.0':
                // TODO update from 1.1.0 to 1.2.0

            case '1.2.0':
                $this->setVar('defaultMessageSortingBackend', 'articledatetime');
                // no break
            case '1.2.1':
                try {
                    $this->schemaTool->create([
                        ImageEntity::class
                    ]);
                } catch (\Exception $exception) {
                    $this->addFlash('error', $this->__('Doctrine Exception') . ': ' . $exception->getMessage());
                    $logger->error(
                        '{app}: Could not create the database tables during installation.'
                            . ' Error details: {errorMessage}.',
                        ['app' => 'MUNewsModule', 'errorMessage' => $exception->getMessage()]
                    );

                    throw $exception;
                }
                $this->setVar('enableShrinkingForImageTheFile', false);
                $this->setVar('shrinkWidthImageTheFile', 800);
                $this->setVar('shrinkHeightImageTheFile', 600);
                $this->setVar('thumbnailModeImageTheFile', 'inset');
                $this->setVar('enabledFinderTypes', 'message###image');
                // no break
            case '1.2.5':
                // for later updates
        }

        // update successful
        return true;
    }
}
